# Stage 1: Build the React application
FROM node:20-alpine AS builder

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm i --production
RUN npm i -g nx

COPY . .

RUN nx reset
RUN nx run notes-ui:build

# Stage 2: Nginx setup
FROM nginx:stable-alpine AS nginx

# Copy the built React app from the previous stage
COPY --from=builder /app/dist/apps/notes-ui /usr/share/nginx/html

# Copy custom Nginx configuration
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 8080

# Start Nginx when the container starts
CMD ["nginx", "-g", "daemon off;"]
